kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgsql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd 
  volumeMode: Filesystem
